routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CityController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home
Route::get('/', [HomeController::class, 'index'])->name('home');

// Authentication
Route::get('/login', [ProfileController::class, 'getLogin'])->name('get_login');
Route::post('/login', [ProfileController::class, 'postLogin'])->name('post_login');
Route::get('/logout', [ProfileController::class, 'logout'])->middleware('logged')->name('logout');
Route::get('/set_password/{user_id}', [ProfileController::class, 'getSetPassword'])->name('get_set_password');
Route::post('/set_password', [ProfileController::class, 'postSetPassword'])->name('post_set_password');

// Dashboard
Route::get('/dashboard', [ProfileController::class, 'getDashboard'])->middleware('logged')->name('dashboard');

// Resource
Route::middleware('logged')->group(function () {

    Route::get('/clients/filter_by_city', [ClientController::class, 'index'])->name('clients.filter');

    Route::resources([
        'cities'  => CityController::class,
        'clients' => ClientController::class,
        'users'   => UserController::class,
    ]);
});

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;

    protected $table = 'cities';

    protected $fillable = [
        'cod',
        'name',
  	];

    public function clients()
    {
        return $this->hasMany('App\Models\Client','city_id','id');
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\City;
use App\Http\Requests\StoreCityRequest;
use App\Http\Requests\UpdateCityRequest;
use Illuminate\Support\Facades\View;

class CityController extends Controller
{
    public function __construct() 
    {
        View::share('menu_active', 'cities');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities=City::paginate(10);
        return view('cities.index', ['cities'=>$cities]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCityRequest $request)
    {
        $city=City::create([
            'cod'  => $request->cod,
            'name' => $request->name,
        ]);

        return redirect()->route('cities.index')->with(['message_info'=>'La ciudad <b>'.$city->name.'</b> ha sido registrada exitosamente.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {
        return view('cities.edit', ['city'=>$city]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCityRequest $request, $id)
    {
        $city=City::find($id);
        $city->update([
            'cod'  => $request->cod,
            'name' => $request->name,
        ]);

        $city=City::find($id);
        return redirect()->route('cities.index')->with(['message_info'=>'La ciudad <b>'.$city->name.'</b> ha sido actualizada exitosamente.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city)
    {
        $city_name=$city->name;

        if(count($city->clients)>0) {
            return redirect()->route('cities.index')->withErrors(['La ciudad <b>'.$city_name.'</b> no puede ser eliminada, ya que tiene clientes asociados.']);
        }

        $city->delete();
        return redirect()->back()->with(['message_info'=>'La ciudad <b>'.$city_name.'</b> ha sido eliminada exitosamente.']);
    }
}

resources/views/cities/create.blade.php
@extends("layouts.main")

@section("titles")
    <title>Registrar ciudad | Serempre technical test</title>
@endsection

@section("content")
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"><i class="nav-icon fas fa-map"></i> Ciudades</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right ml-1 mt-1">
                        <li class="breadcrumb-item"><a class="btn btn-primary btn-sm" href="{{route('cities.index')}}">Listado</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            @if(session('message_info'))
                <div class="alert alert-success alert-dismissible">
                    <h5><i class="icon fas fa-check"></i> Info</h5>
                    {!!session('message_info')!!}
                </div>
            @endif
            @if($errors->any())
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Error</h5>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="card-title">Registrar</h3>
                </div>
                <form action="{{route('cities.store')}}" method="POST">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-12 col-sm-3 col-md-3">              
                                    <small class="text-muted">* Código</small>
                                    <div class="input-group mb-3">
                                        <input name="cod" type="text" class="form-control" placeholder="Código" value="{{old('cod')}}" required>
                                    </div>
                                </div>                                
                                <div class="col-12 col-sm-3 col-md-3">              
                                    <small class="text-muted">* Nombre</small>
                                    <div class="input-group mb-3">
                                        <input name="name" type="text" class="form-control" placeholder="Nombre" value="{{old('name')}}" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/cities/edit.blade.php
@extends("layouts.main")

@section("titles")
    <title>Editar ciudad | Serempre technical test</title>
@endsection

@section("content")
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"><i class="nav-icon fas fa-map"></i> Ciudades</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right ml-1 mt-1">
                        <li class="breadcrumb-item"><a class="btn btn-primary btn-sm" href="{{route('cities.index')}}">Listado</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            @if(session('message_info'))
                <div class="alert alert-success alert-dismissible">
                    <h5><i class="icon fas fa-check"></i> Info</h5>
                    {!!session('message_info')!!}
                </div>
            @endif
            @if($errors->any())
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Error</h5>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="card-title">Editar</h3>
                </div>
                <form action="{{route('cities.update',[$city->id])}}" method="POST">
                    @csrf
                    @method("PUT")
                    <input name="city_id" type="hidden" value="{{$city->id}}">
                    <div class="card-body">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-12 col-sm-3 col-md-3">              
                                    <small class="text-muted">* Código</small>
                                    <div class="input-group mb-3">
                                        <input name="cod" type="text" class="form-control" placeholder="Código" value="{{$city->cod}}" required>
                                    </div>
                                </div>                                
                                <div class="col-12 col-sm-3 col-md-3">              
                                    <small class="text-muted">* Nombre</small>
                                    <div class="input-group mb-3">
                                        <input name="name" type="text" class="form-control" placeholder="Nombre" value="{{$city->name}}" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/cities/index.blade.php
@extends("layouts.main")

@section("titles")
    <title>Ciudades | Serempre technical test</title>
@endsection

@section("content")
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"><i class="nav-icon fas fa-map"></i> Ciudades</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right ml-1 mt-1">
                        <li class="breadcrumb-item"><a class="btn btn-primary btn-sm" href="{{route('cities.create')}}">Registrar</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            @if(session('message_info'))
                <div class="alert alert-success alert-dismissible">
                    <h5><i class="icon fas fa-check"></i> Info</h5>
                    {!!session('message_info')!!}
                </div>
            @endif
            @if($errors->any())
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Error</h5>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{!!$error!!}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="table-responsive">
                <table id="table-list" class="table table-bordered table-sm display table-hover table-serempre" cellspacing="0" width="100%">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Código</th>
                            <th>Nombre</th>
                            <th>Clientes asociados</th>
                            <th>Fecha y hora de registro</th>
                            <th class="text-center">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($cities as $city)
                            <tr>
                                <td>{{$city->id}}</td>
                                <td>{{$city->cod}}</td>
                                <td>{{$city->name}}</td>
                                <td>{{$city->clients->count()}}</td>
                                <td>{{$city->created_at->format('d/m/Y h:i:s a')}}</td>
                                <td>
                                    <a class="btn btn-sm btn-warning mr-1 d-inline" href="{{route('cities.edit',$city->id)}}">
                                        <i class="fa fa-edit" aria-hidden="true"></i>
                                    </a>
                                    <form class="d-inline" action="{{route('cities.destroy', [$city->id])}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-sm btn-danger">
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{$cities->links()}}
            </div>
        </div>
    </section>
@endsection